osx_image: xcode8
language: objective-c

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod repo update --silent
  - pod install --project-directory=Example

script:
  - set -o pipefail
  - >-
    xcodebuild clean build test
    -workspace Example/Lstn.xcworkspace
    -scheme LstnExample
    -sdk iphonesimulator10.0
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
    -skip-testing:LstnTests/AudioEngineSpec
    -skip-testing:LstnTests/PlayerSpec

  - pod lib lint

# deploy:
#   provider: script
#   script: pod trunk push Lstn.podspec
#   skip_cleanup: true
#   on: { tags: true }

notifications:
  email: false
