osx_image: xcode8
language: objective-c

xcode_project: LstnSDK.xcodeproj
xcode_scheme: LstnSDK

before_install:
  - gem update cocoapods --prerelease
  - bundle exec pod repo update
  - bundle exec pod install --project-directory=Example

script:
  - >-
    xcodebuild clean build test
    -workspace Example/Lstn.xcworkspace
    -scheme LstnExample
    -sdk iphonesimulator10.0
    -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0'
  - pod lib lint

deploy:
  provider: script
  script: bundle exec pod trunk push Lstn.podspec
  on: { tags: true }

notifications:
  email: false
